In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#display setting
pd.set_option('display.max_columns', None)
sns.set(style="whitegrid")

In [2]:
df = pd.read_csv('EmadeStore.csv', encoding='latin1')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [3]:
#show values in column
df['Segment'].unique()

array(['Consumer', 'Corporate', 'Home Office'], dtype=object)

In [4]:
#Dictionary
df1 = {
    'Customer Name' : ['Claire Gute', 'Darrin Van Huff',
                       "Sean O'Donnell", 'Dave Brooks', 'Chris Cortes'],
    'City' : ['Las Vegas', 'Pasadena', 'Philadelphia', 'Colorado Springs', 'Tampa']
}

#Create a dataframe
df1 = pd.DataFrame(df1,
                   columns = ['Customer Name', 'City']
                  )

In [5]:
df1

     Customer Name              City
0      Claire Gute         Las Vegas
1  Darrin Van Huff          Pasadena
2   Sean O'Donnell      Philadelphia
3      Dave Brooks  Colorado Springs
4     Chris Cortes             Tampa

In [6]:
#Dictionary
df2 = {
    'Segment' : ['Consumer', 'Corporate', 'Consumer', 'Home Office', 'Consumer'],
    'Customer Name' : ['Claire Gute', 'Darrin Van Huff',
                       "Sean O'Donnell", 'Dave Brooks', 'Chris Cortes'],
    'City' : ['Las Vegas', 'Pasadena', 'Philadelphia', 'Colorado Springs', 'Tampa'],
    'State' : ['Nevada', 'California', 'Pennsylvania', 'Colorado', 'Florida'],
    'Country' : ['United States', 'United States', 'United States','United States', 'United States']
}

#Create a dataframe
df2 = pd.DataFrame(df2,
                   columns = ['Segment','Customer Name', 'City', 'State', 'Country']
                  )
print('DataFrame Created')

DataFrame Created

In [7]:
df2

       Segment    Customer Name              City         State        Country
0     Consumer      Claire Gute         Las Vegas        Nevada  United States
1    Corporate  Darrin Van Huff          Pasadena    California  United States
2     Consumer   Sean O'Donnell      Philadelphia  Pennsylvania  United States
3  Home Office      Dave Brooks  Colorado Springs      Colorado  United States
4     Consumer     Chris Cortes             Tampa       Florida  United States

In [8]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [9]:
#Checking for distinct values
df['Product Name'].unique()

array(['Bush Somerset Collection Bookcase',
       'Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back',
       'Self-Adhesive Address Labels for Typewriters by Universal', ...,
       'Eureka Hand Vacuum, Bagless', 'LG G2',
       'Eldon Jumbo ProFile Portable File Boxes Graphite/Black'],
      dtype=object)

In [10]:
#returning particular row of a column with the row number (direct indexing)
df.at[9992, "Product Name"]     # Row 9992, column "Age"

'It\'s Hot Message Books with Stickers, 2 3/4" x 5"'

In [11]:
#Dictionary
df3 = {
    'Category' : ['Furniture', 'Furniture', 'Office Supplies', 'Technology', 'Office Supplies'],
    'Sub-Category' : ['Bookcases', 'Chairs', 'Labels', 'Phones', 'Appliances'],
    'Product Name' : ['Bush Somerset Collection Bookcase', 'Hon Deluxe Fabric Upholstered Stacking Chairs', 
                      'Self-Adhesive Address Labels for Typewriters by Universal', 'Aastra 57i VoIP phone',
                      "It's Hot Message Books with Stickers, 2 3/4 x 5"],
    'Sales': ['261.9600', '731.9400', '14.6200', '258.5760', '29.6000'],
    'Quantity' : ['2','3','2','2','4']
}

#Create DataFrame
df3 = pd.DataFrame(df3,
                   columns = ['Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity']
                  )

#Calculating price and converting sales and quantity columns to numeric
df3['Price'] = (pd.to_numeric(df3['Sales']) * pd.to_numeric(df3['Quantity']))

#ANOTHER WAY. converting seperately before calculating
# Convert Sales and Quantity columns to numeric values
#df3['Sales'] = pd.to_numeric(df3['Sales'])
#df3['Quantity'] = pd.to_numeric(df3['Quantity'])

# Calculate price by multiplying Sales and Quantity 
#df3['Price'] = df3['Sales'] * df3['Quantity']

In [12]:
df3

,Category,Sub-Category,Product Name,Sales,Quantity,Price
0,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,523.920
1,Furniture,Chairs,Hon Deluxe Fabric Upholstered Stacking Chairs,731.9400,3,2195.820
2,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,29.240
3,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,517.152
4,Office Supplies,Appliances,"It's Hot Message Books with Stickers, 2 3/4 x 5",29.6000,4,118.400